// Samtliga texter till ICC Hemsida
      var arrWords = [
	 // GLOBAL
      	new langObject(0, "Innehåll:", "Content:"),
      	new langObject(1, "<b>adress.</b> Lagerlöfsgatan 8, 112 60 Stockholm ", "<b>address.</b> Lagerlofsgatan 8, S-112 60 Stockholm, <small>SWEDEN</small> "),
      	new langObject(2, "<b>tel.</b> 08-546 660 60 ", "<b>phone.</b> +46 8 546 660 60 "),
      	new langObject(3, "<b>fax.</b> 08-546 660 01 ", "<b>fax.</b> +46 8 546 660 01 "),
      	new langObject(4, "<b>e-post.</b> <a href=\"mailto:icc@ipso.cc\">icc@ipso.cc</a>", "<b>e-mail.</b> <a href=\"mailto:icc@ipso.cc\">icc@ipso.cc</a>"),
      	new langObject(5, "Meny", "Menu"),
      	new langObject(6, "Välkommen till IPSO Classification & Control", "Welcome to IPSO Classification & Control"),
      	new langObject(7, "Tillbaka", "Back"),
		
	// OM ICC
      	new langObject(1000, "Om ICC", "About ICC"),
      	new langObject(1100, "Företaget", "Company"),
	      	new langObject(1101, "<strong>ICC</strong> är ett konsultföretag som arbetar med processtyrning och tillförlitlighet.<br><br><strong>ICC</strong> är framförallt är verksamt inom process- och tillverkningsindustri men erfarenheter finns även från tjänsteföretag samt offentliga verksamheter.<br><br><strong>ICC</strong> som avkoppades från \"Institutet för Personsäkerhet och Olycksfallsforskning\" ingår i ett nätverk där kompetens och lång erfarenhet finns från industriell verksamhet och forskning. Resurser sätts samman för bästa anpassning till varje uppdrag vilket gör ICC till en värdefull partner i de flesta produktions- och organisationsutvecklande projekt.", "<strong>ICC</strong> is a private company acting in the fields of reliability, process control and safety.<br><br><strong>ICC</strong> is departed from IPSO, the Institute Human Safety and Accident Research, in order to implement the results from the research into practice.<br><br>With this scientific background and long industrial experience, ICC can, together with experts in its network, set up the best competence profil for every assignment."),
			new langObject(1102, "För information om kontoret samt karta se: <a href=\"http://www.livecomoffice.se/\" target=\"_new\">livecomoffice.se</a>", "For information about the office facilities visit:<br><a href=\"http://www.livecomoffice.se/\" target=\"_new\">livecomoffice.se</a> (site in swedish)"),
      	new langObject(1200, "Medarbetare", "Co-Workers"),
			new langObject(1201, "Det är vi som arbetar på ICC:", "We work at ICC:"),
			new langObject(1202, "VD, Civilingenjör<br>08-546 660 66", "Manging Director, M SC Naval Architecture and Marine Engineering<br>+46 8 546 660 66"),
			new langObject(1203, "Sjöingenjör<br>08-546 660 60", "Project Leader, Marin Engineer<br>+46 8 546 660 60"),
			new langObject(1204, "Projektledare, Civilingenjör<br>08-546 660 60", "Project Leader, M.Sc. Process Development<br>+46 8 546 660 60"),
			new langObject(1205, "Mariningenjör<br>08-546 660 60", "Project Leader, Naval architect and Marine Engineer<br>+46 8 546 660 60"),
			new langObject(1206, "<br>08-546 660 60", "Project Leader, Navy Officer<br>+46 8 546 660 60"),
			new langObject(1207, "Webbutvecklare/Grafiker<br>026-10 24 90", "Webdeveloper/designer<br>+46 26 10 24 90"),
        new langObject(1300, "Samarbetspartners", "Business Partners"),
			new langObject(1301, "<b>Ampere Media</b><br><br>Ampere Media producerar interaktiva instruktioner och utbildningar samt databassystem.", "<b>Ampere Media</b><br><br>produces interactive multimedia instruction, manuals, training programs as well as database systems."),
			new langObject(1302, "www.amperemedia.se", "www.amperemedia.se"),
			new langObject(1303, "<b>Safety C</b><br><br>I Safety C jobbar Thomas Norelöv och Kent Melander som har ett förflutet i Marinen sen 1961. Deras specialiteter finns inom arbetsmiljö, fartygssäkerhet och brandskydd. De är samlokaliserade med ICC och driver flera projekt tillsammans.", "<b>Safety-C</b><br>Safety C employs Thomas Norelöf  and Kent Melander and  the focus is Safety at Sea, Fire Fighting and Working Environment issues."),
		
	// TJÄNSTER
      	new langObject(2000, "Tjänster", "Services"),
		new langObject(2100, "Processutveckling","Process Development"),
			new langObject(2101, "För att ständigt förbättra en verksamhet måste de viktigaste processerna kontinuerligt styras avseende följande aspekter:<br><br><div style=\"color:black;\"><b>P</b> - produktion och tillförlitlighet</div><div style=\"color:blue;\"><b>Q</b> - kvalitet</div><div style=\"color:red;\"><b>S</b> - säkerhet och hälsa</div><div style=\"color:green;\"><b>E</b> - yttre miljö</div><br>","To continously improve performance of business, services or operations the most important work proscesses and procedures have to be controlled in all following aspects:<br><br><div style=\"color:black;\"><b>P</b> - Production and reliability</div><div style=\"color:blue;\"><b>Q</b> - Quality</div><div style=\"color:red;\"><b>S</b> - Safety&Health, Security</div><div style=\"color:green;\"><b>E</b> - Environment</div><br>"),
			new langObject(2102, "Målet med processutveckling-<small>PQSE</small> är att utifrån en helhetssyn styra verksamheten så att personalen utför de mest kritiska arbetsuppgifterna på \"bästa sätt\". Processutveckling-<small>PQSE</small> startar med att den erfarna personalens kunskap om vad som är kritiska arbetsuppgifter sammanställs. Sedan formuleras \"bästa sätt\" att utföra dessa arbetsuppgifter i form av instruktioner, utbildningar, manualer etc. Beskrivningar av \"bäst sätt\" görs slutligen tillgänglig för alla som behöver ta del av informationen i form av multimedia via cd-rom, Intranet eller Internet.<br><br>","The aim with a <small>PQSE</small> development of a process is to control, on the basis of an overall view, that all critical tasks are performed according to what is \"Best Practice\". The development starts with collection of the experienced and skilled operators and crews knowledge of how to manage critical events in the best way. This knowledge is formulated in multi-media based descriptions, instructions, manuals, training materials, etc. \"Best Practice\" is communicated on Internet/intranet or CD-Rom."),
			new langObject(2103, "Multimediabeskrivningar av \"bästa sätt\" kan med fördel användas som ett komplement till ledningssystem av typen <small>ISO 9000</small> och <small>ISO 14 000</small> samt vid upprättandet av kompetens och bemanningsprofiler, utbildningsprogram för kompetensutveckling m.m. För att styra insatserna vid utvecklingen av verksamhetens processer bör detta arbete kombineras med en erfarenhetsbank, se: <a href=2300.html>Erfarenhetsbank-PQSE</a><br><br><b><small>REFERENSPROJEKT:</small></b> Smålandshamnar | Silja","Multi-media based \"Best Practice\" may be a part of Quality Management systems as <small>ISO 9000</small> and <small>ISO 14000</small> as well establishing of competence profiles, education- and training programmes.<br><br><b><small>REFERENCE:</small></b> Smålandshamnar | Silja<br><br>To control the steps of progress the experiences made should be recorded and shared within the organisation in an \"Experince Data Bank\", see <a href=2300.html>Experience Data Bank - <small>PQSE</small></a>"),
		new langObject(2200, "Produktbeskrivningar","Description of Products"),
			new langObject(2201, "För att en produkt skall kunna användas på bästa sätt måste informationen förmedlas avseende följande aspekter:<br><br><div style=\"color:black;\"><b>P</b> - Hur man använder produkten, gör service och underhåll</div><div style=\"color:blue;\"><b>Q</b> - Information om garantier kundkontakt</div><div style=\"color:red;\"><b>S</b> - Säkerhetsinstruktion</div><div style=\"color:green;\"><b>E</b> - Ekologi, produktens påverkan den yttre miljön, Återvinning</div><br>", "To ensure that a product is used according to its design critera, relevant and proper instructions and manuals should be provided and reflect several aspects:<br><br><div style=\"color:black;\"><b>P</b> - The intentional use and the maintenance of the product</div><div style=\"color:blue;\"><b>Q</b> - Information about warranty and customer support</div><div style=\"color:red;\"><b>S</b> - Safety warnings and Health hazards</div><div style=\"color:green;\"><b>E</b> - Ekologi, Environment and Recycling</div><br>"),
			new langObject(2202, "Målet med produktbeskrivning-<small>PQSE</small> är att utifrån en helhetssyn informera användarna om hur produkten används på bästa sätt.<br><br>Informationen kan formuleras i form av varningstexter, instruktioner, utbildningar, manualer etc. som görs tillgänglig för alla användare i form av multimedia via cd-rom, Intranet eller Internet.<br><br><b><small>REFERENSPROJEKT</small></b>: FMV Flykthuva", "The aim with a <small>PQSE</small> – description of a product is to control that the product when it is used as intented is safe and fulfill Ouality and Environment Standards.<br><br>The information is formulated in multi-media based descriptions, instructions, manuals, training materials, etc and are communicated on Internet/intranet or <small>CD</small>-rom."),
		new langObject(2300, "Erfarenhetsbanker","Experience Data Bank"),
			new langObject(2301, "Det finns många goda skäl att ta lärdom av vunna erfarenheter. Med en erfarenhetsbank kan information om oönskade händelser samlas in och analyseras i syfte att förhindra att liknande händelse inträffar igen. För att ständigt förbättra en verksamhet bör erfarenheter kontinuerligt samlas in avseende följande aspekter:<br><br><div style=\"color:black;\"><b>P</b> - produktion och tillförlitlighet</div><div style=\"color:blue;\"><b>Q</b> - kvalitet</div><div style=\"color:red;\"><b>S</b> - säkerhet och hälsa</div><div style=\"color:green;\"><b>E</b> - yttre miljö</div><br>", "There are many reasons to learn from the experience. With an Experience Data Bank, information of near misses and unwanted events can be collected and analyzed in order to prevent reiteration.<br><br>To continously improve performance of business, services or operations the experience of failures, misses, deviations and incidents be recorded and classified according to:<br><br><div style=\"color:black;\"><b>P</b> - Production and reliability</div><div style=\"color:blue;\"><b>Q</b> - Quality</div><div style=\"color:red;\"><b>S</b> - Safety&Health, Security</div><div style=\"color:green;\"><b>E</b> - Environment</div><br>"),
			new langObject(2302, "Erfarenhetsbanken-<small>PQSE</small> är en databas tillgänglig för rapportering och sökning av information via Intranet eller Internet.<br><br><small><b>REFERENSPROJEKT:</b></small> INSJÖ - Informationssystemet om incidenter i sjöfarten.<br>Se: <a href=\"http://www.insjo.org/\" target=\"_new\">www.insjo.org</a>", "The Experience Data Bank - <small>PQSE</small> is a database, accessible 24 hours a day, for reporting and searching via Internet/Intranet<br><br><small><b>REFERENCE:</b></small> INSJO, the Reporting System for Incidents &Near Misses at Sea.<br>See: <a href=\"http://www.insjo.org/\" target=\"_new\">www.insjo.org</a>"),
		new langObject(2400, "Utvärderingar","Safety Assessments & Risk Analysis"),
			new langObject(2401, "<small>ICC</small> utvärderar och reviderar funktionen hos ledningssystem som upprättas enligt standarder som t.ex. <small>ISO 9000:2000, ISO 14 000, AFS 2001:1</small> och <small>OHSAS 18001</small>.<br><br><small>ICC</small> är licensierad användare av det kanadensiska utvärderingsinstrumentet Impact <small>2000</small> vilket används vid utvärdering av funktionen hos ledningssystem för arbetsmiljö och säkerhet.", "<small>ICC</small> performs Safety Assessements and Risk Analysis  mainly within the process- and manufacturing industry and transport sector.i.e. shipping.<br><br><small>ICC</small> evaluates and assesses the performance of productionsystems, functions of managementsystems and the reliability of single components as well as whole systems."),
/*		new langObject(2500, "Utredningar","Inquiries"),
			new langObject(2501, "<small>ICC</small> utför utredningar inom en rad områden inom process- och tillverkningsindustrin för att förbättra produktivitet, säkerhet och kvalitet.<br><br><small>ICC</small> har genom sitt ursprung från \"Institutet för personsäkerhet och olycksfallsforskning\" lång erfarenhet från att inventera och analysera risker för personskador inom vitt skilda verksamhetsområden.<br><br>Resultatet av en utredning är vanligtvis en rapport som avser att fungera som ett beslutsunderlag vid förändring i verksamheten. Vid utredning av hur nya datasystem skall utfomas är esultatet inte en rapport utan en prototyp som visar hur det riktiga systemet bör vara utformat, se: <a href=../../incl//"2600.html/">Prototyping</a>.", "-"),
		new langObject(2600, "Prototyping","Prototyping"),
			new langObject(2601, "Ett kostnadseffektivt sätt att utveckla ett nytt datasystem är att först utveckla en prototyp.<br><br>Prototypen är aldrig detsamma som det riktiga datasystemet utan vanligtvis en skiss i form av skärmbilder som visualiserar hur detta bör vara utformat vad gäller funktion och design.<br><br>En väl genomtänkt prototyp kan användas som en del i kravspecifikationen för det riktiga datasystemet och fungerar som en viktig del i kommunikationen mellan användare och tillverkare av systemet.<br><br><small>ICC</small> har i ett flertal projekt använt prototyping som metod att visualisera resultatet av en utredning i syfte att upprätta en tydlig kravspecifikation för ett nytt datasystem.<br><br><small><b>REFERENSPROJEKT:</b></small> INSJÖ - Informationssystemet om incidenter i sjöfarten | Incidentrapportering via internet (Enköpingskommun)", "-"),		
*/
		new langObject(2700, "Interaktiva instruktioner och utbildningar","Interactive instructions and e-learning"),
			new langObject(2701, "<small>ICC</small> producerar tillsammans med Ampere Media interaktiva instruktioner och utbildningar samt databassystem.", "<small>ICC</small> produces interactive descriptions, instructions, manuals and databases in cooperation with Ampere Media AB"),
		
	// REFERENSER
      	new langObject(3000, "Referenser", "References"),
      	new langObject(3100, "Företag", "Clients"),
			new langObject(3101, "Sedan starten <small>1994</small> har <small>ICC</small> anlitas av ett fyrtiotal företag och organisationer:", "-"),
      	new langObject(3200, "Projekt", "Projects"),
			new langObject(3201, "Ett urval av projekt som <small>ICC</small> har genomfört:", "A selection of projects by <small>ICC</small>:"),
			new langObject(3202, "<b>INSJÖ - Informationssystemet om incidenter i sjöfarten</b>", "<b>INSJO - Informationssystem for reporting incidents at Sea</b>"),
			new langObject(3203, "<b>Silja</b>:<br>Familiarization Training / Crowd Management / Fire Fighting Training", "<b>Silja</b>:<br>Familiarization Training / Crowd Management / Fire Fighting Training"),
			new langObject(3204, "<b>FMV</b>: Flykthuva 15", "<b>FMV</b>: Flykthuva 15"),
			new langObject(3205, "<b>Smålandshamnar</b>", "<b>Smalandshamnar</b>"),
//			new langObject(3206, "<b>Enköpingskommun</b>: Incidentrapportering via internet", "<b>Enkopingskommun</b>: "),
			new langObject(3207, "<small>INSJÖ</small> är ett utvecklingsprojekt för alla i sjöfartsnäringen som vill bidra eller ta del av information om kritiska händelser som inträffat till sjöss samt utbyta idéer om hur sjösäkerheten för svenska fartyg skall förbättras.<br><br><small>ICC</small> har i samarbete med Sveriges Redareförening och Sjöfartsverket utvecklat den erfarenhetsbank som utgör kärnan i <small>INSJÖ</small>. Erfarenhetsbanken är en <small>SQL</small>-databas tillgänglig för rapportering och sökning via internet.<br><br>Informationen i erfarenhetsbanken avser att ge beslutsfattare i branschen bättre underlag att bedöma säkerhets- och miljörisker så att lämpliga förebyggande åtgärder kan vidtas.<br><br>För mer information om <small>INSJÖ</small> se: <a href=\"http://www.insjo.org/\" target=\"_new\">www.insjo.org</a>", "")
      ];
	
	// gör objektmall
	function langObject(tId,tSwe,tEng){
	  this.tId = tId;
	  this.swe = tSwe;
	  this.eng = tEng;
	}